# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NEMeetingDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NEMeetingSDK', '~> 1.8.1'
  pod 'XLForm', '~> 4.1.0'
  pod 'IQKeyboardManager', '~> 6.5.6'
  pod 'Masonry', '~> 1.1.0'
  
  # Pods for NEMeetingDemo

end
