# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'NEMeetingDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!
  
  pod 'XLForm', '~> 4.1.0'
  pod 'IQKeyboardManager', '~> 6.5.6'
  pod 'Masonry', '~> 1.1.0'
  pod 'Reachability'
  
  pod 'NEMeetingKit', '~> 4.9.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ENABLE_BITCODE"] = "NO"
      config.build_settings["APPLICATION_EXTENSION_API_ONLY"] = "NO"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
