# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NEMeetingDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'NEMeetingSDK', '~> 3.4.2'
  pod 'NEMeetingSDK', '~> 1.2.0'

  pod 'XLForm', '~> 4.1.0'

  pod 'IQKeyboardManager'

  # Pods for NEMeetingDemo

end
